#!/usr/bin/env python3

import webbrowser
import sys
import os

def open_urls_in_chromium(urls_file):
    with open(urls_file, 'r') as file:
        urls = file.read().split(',')
        urls = [url.strip() for url in urls]

        for url in urls:
            webbrowser.get('chromium').open_new_tab(url)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./test.py <urls_file>")
        sys.exit(1)

    urls_file = sys.argv[1]

    # Set the WEBBROWSER_OPEN_DELAY environment variable to a shorter delay
    os.environ['WEBBROWSER_OPEN_DELAY'] = '0.1'  # Adjust the delay here (in seconds)
    
    open_urls_in_chromium(urls_file)
